site_name: YUMI-LAB documentation
repo_url: https://github.com/Yumi-Lab/Yumi-Smart-Pi.git
repo_name: Yumi-Lab/Yumi-Smart-Pi

# Website layout configuration (using mkdocs-material theme)
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  logo: ../img/YUMI_LOGO.svg
  favicon: ../img/favicon.ico
  icon:
    repo: fontawesome/brands/github
    alternate: material/web
  features:
      #- navigation.tabs
      #- navigation.expand
      - navigation.top
      # if enabled, the TOC doesn't work for some pages
      # - toc.integrate
      - search.suggest
      - search.highlight
      - search.share
  language: en
extra_css:
  - css/extra.css

nav:
  - YUMI SBC nano-computer:
    - SMART PI ONE:
      - SmartPI/SmartPi_One_specifications.md
      - SmartPI/SmartPi_Klipper.md
      - SmartPI/SmartPi_Retro_Gaming.md
      - SmartPI/SmartPi_Home_Assistant.md
      - SmartPI/SmartPi_Linux_Desktop.md
      - SmartPI/SmartPi_Linux_server.md
  - YUMI others Components:
    - Yumi_Components/SmartLCD_Touch_4.3inch800x480specifications.md
    - Yumi_Components/SmartPI/SmartHub_specifications.md
    - Yumi_Components/SmartPI/SmartShield_specifications.md
  - YUMI Klipper SMART PAD:
    - KlipperSmartPad/SmartPad_specifications.md
    - 1.PRINTERS:
      - PRINTERS/SIDEWINDER_X2.md
      - PRINTERS/PRUSA_MK3.md
   - YUMI LAB mobile APP:

